Repository Softawii/curupira, pull requests merged in 2022-07, with the labels that each got.

#19 feat: maven? github packages? god bless you
  .github/workflows/publish.yml
  build.gradle
Labels: enhancement, help wanted

#25 feat: jitpack support
  .github/workflows/publish.yml
  build.gradle
  jitpack.yml
Labels: enhancement

#27 registering in inner class closes #26
  build.gradle
  src/main/java/com/softawii/curupira/core/Curupira.java
Labels: bug

#28 registering in inner class closes (lol) #26
  build.gradle
  src/main/java/com/softawii/curupira/core/Curupira.java
Labels: bug

#31 fix: add voice channel to PUBLIC_CHANNELS list
  .github/workflows/gradle.yml
  src/main/java/com/softawii/curupira/core/CommandHandler.java
Labels: bug
